#ifndef SMCF_REGISTER_H
#define SMCF_REGISTER_H

#define MGI_GRP_ID          (0x000)                 /* RO */
#define MGI_DATA_INFO       (0x008)                 /* RO */
#define MGI_FEAT0           (0x010)                 /* RO */
#define MGI_FEAT1           (0x018)                 /* RO */
#define MGI_SMP_EN          (0x030)                 /* RW */
#define MGI_SMP_CFG         (0x038)                 /* RW */
#define MGI_SMP_PER         (0x040)                 /* RW */
#define MGI_SMP_DLY         (0x048)                 /* RW */
#define MGI_MON_REQ         (0x060)                 /* RW */
#define MGI_MON_STAT        (0x070)                 /* RO */
#define MGI_MODE_BCAST      (0x080)                 /* RW */
#define MGI_MODE_REQ(n)     (0x090 + (8 * (n)))     /* RW */
#define MGI_MODE_STAT(n)    (0x0C0 + (8 * (n)))     /* RO */
#define MGI_IRQ_STAT        (0x100)                 /* RW */
#define MGI_IRQ_MASK        (0x110)                 /* RW */
#define MGI_TRG_MASK        (0x140)                 /* RW */
#define MGI_ERR_CODE        (0x150)                 /* RO */
#define MGI_WREN            (0x160)                 /* RW */
#define MGI_WRCFG           (0x168)                 /* RW */
#define MGI_WADDR0          (0x170)                 /* RW */
#define MGI_WADDR1          (0x174)                 /* RW */
#define MGI_RADDR0          (0x180)                 /* RW */
#define MGI_RADDR1          (0x184)                 /* RW */
#define MGI_DISCON_ID       (0x190)                 /* RO */
#define MGI_CON_STAT        (0x198)                 /* RO */
#define MGI_CMD_SEND0       (0x1B0)                 /* RW */
#define MGI_CMD_SEND1       (0x1B8)                 /* RW */
#define MGI_CMD_RECV0       (0x1C0)                 /* RO */
#define MGI_CMD_RECV1       (0x1C8)                 /* RO */
#define MGI_ATYP(n)         (0x200 + (16 * (n)))    /* RW */
#define MGI_AVAL_LOW(n)     (0x208 + (16 * (n)))    /* RW */
#define MGI_AVAL_HIGH(n)    (0x20C + (16 * (n)))    /* RW */
#define MGI_DATA(n)         (0x700 + (4 * (n)))     /* RO */
#define MGI_DVLD            (0xF00)                 /* RO */
#define MGI_TAG0            (0xF10)                 /* RO */
#define MGI_TAG1            (0xF14)                 /* RO */
#define MGI_TAG2            (0xF18)                 /* RO */
#define MGI_TAG3            (0xF1C)                 /* RO */
#define MGI_SMPID_START     (0xF40)                 /* RO */
#define MGI_SMPID_END       (0xF48)                 /* RO */
#define MGI_IIDR            (0xFC0)                 /* RO */
#define MGI_AIDR            (0xFC8)                 /* RO */

typedef union {
    uint32_t value;
    struct {
        uint32_t grp_id             : 12;   /* Monitor Group Interface Identifier Value */
        uint32_t res0               : 4;
        uint32_t mon_num            : 5;   /* Specifies the number of Monitors in the MGI.
                                              The number of monitors in the MGI is MON_NUM + 1. */
        uint32_t res1               : 11;
    } bits;
} smcf_mgi_grp_id_t;

typedef union {
    uint32_t value;
    struct {
        uint32_t data_per_mon       : 16;   /* The number of data values generated per monitor for each sample.
                                               The number of data values generated is DATA_PER_MON + 1. */
        uint32_t res0               : 4;
        uint32_t packed             : 1;    /* Packed Bit.
                                               This indicates multiple monitor data values are placed in a single 32-bit register. */
        uint32_t alt_addr           : 1;    /* Alternate Address Bit.
                                               0b0 : Monitor data is read from MGI_DATA<n>.
                                               0b1 : Monitor data is read from the address in MGI_RADDR0 / MGI_RADDR1.*/
        uint32_t mon_data_width     : 6;    /* The bit width of the data values generated by each monitor.
                                               The data value width is MON_DATA_WIDTH + 1. */
        uint32_t res1               : 4;
    } bits;
} smcf_mgi_data_info_t;

typedef union {
    uint32_t value;
    struct {
        uint32_t alert_num          : 3;    /* Indicates the number of supported alerts. */
        uint32_t tag_len            : 7;    /* Indicates the bit width of the tag value if present, indicated by TAG_IN.
                                               The tag length is TAG_LEN+1.
                                               If TAG_LEN < 32 then MGI_TAG1 is RES0.
                                               If TAG_LEN < 64 then MGI_TAG2 is RES0.
                                               If TAG_LEN < 96 then MGI_TAG3 is RES0.*/
        uint32_t res0               : 8;
        uint32_t single_mon_mode    : 1;    /* Indicates if the MGI supports only a single monitor mode setting for all monitors or allows separate settings for each monitor.
                                               If SINGLE_MON_MODE = 0b1 then MGI_MODE_BCAST is RES0.
                                               0b0 : The MGI supports separate mode settings for each monitor.
                                               0b1 : The MGI only supports a single mode setting for all monitors.*/
        uint32_t alt_delta          : 1;    /* Indicates if the alert rising and falling delta functions are supported.
                                               0b0 : The alert rising and falling delta functions are not present.
                                               0b1 : The alert rising and falling delta functions are present.*/
        uint32_t tag_in             : 1;    /* Indicates if the tag input is present.
                                               0b0 : The tag input is not present.
                                               0b1 : The tag input is present. */
        uint32_t trig_in            : 1;    /* Indicates if the trigger input is present.
                                               0b0 : The trigger input is not present.
                                               0b1 : The trigger input is present. */
        uint32_t trig_out           : 1;    /* Indicates if the output trigger is present.
                                               0b0 : The output trigger is not present.
                                               0b1 : The output trigger is present. */
        uint32_t dma_if             :1;     /* Indicates if the DMA interface is present.
                                               0b0 : The DMA interface is not present.
                                               0b1 : The DMA interface is present. */
        uint32_t user_def_cmd       : 1;    /* Indicates if User Defined commands are supported.
                                               0b0 : User Defined commands are not supported.
                                               0b1 : User Defined commands are supported. */
        uint32_t mon_discon         : 1;    /* Indicates if disconnection is supported for any monitor.
                                               Information on disconnection support for each monitor can be read from MGI_DISCON_ID.
                                               0b0 : Disconnection is not supported on any monitors.
                                               0b1 : Disconnection is supported on one or more monitors.*/
        uint32_t per_timer          : 1;    /* Indicates if the periodic timer is present.
                                               0b0 : The periodic timer is not present.
                                               0b1 : The periodic timer is present. */
    } bits;
} smcf_mgi_feat0_t;

typedef union {
    uint32_t value;
    struct {
        uint32_t mode_reg           : 3;    /* Indicates the number of Monitor Mode Request and Status Registers. */
        uint32_t res0               : 5;
        uint32_t mode_len           : 5;    /* Indicates the bit width of each of the Monitor Mode Request and Status Registers.
                                               The number of bits in each register is MODE_LEN + 1 */
        uint32_t res1               : 3;
        uint32_t smp_dly_len        : 6;    /* Indicates the number of bits in the Sample Delay Register.
                                               If SMP_DLY_LEN = 0b000000 then MGI_SMP_DLY is RES0.
                                               If SMP_DLY_LEN > 0b000000 then MGI_SMP_DLY is SMP_DLY_LEN bits wide.
                                               Values greater than 0b100000 are reserved. */
        uint32_t res2               : 10;
    } bits;
} smcf_mgi_feat0_t;

typedef union {
    uint32_t value;
    struct {
        uint32_t en                 : 1;    /* Sample Enable
                                               Enables monitor sampling.*/
        uint32_t og                 : 1;    /* Sample Ongoing.
                                               Indicates when monitor sampling is ongoing.
                                               This bit is read only.
                                               For a single monitor sample (MGI_SMP_CFG.SMP_TYP = 0b00) this is 0b1 when the monitor sample is ongoing,
                                               then goes LOW when it is complete.
                                               For other monitor sample types this is set to 0b1 when the monitor sample enable (MGI_SMPEN.EN) is set to 0b1.
                                               It is set to 0b0 when the sample enable is set to 0b0 and a monitor sample is not currently ongoing. */
        uint32_t res0               : 30;
    } bits;
} smcf_mgi_smp_en_t;

#endif  //!SMCF_REGISTER_H
