# Copyright (c) 2026 simple-boot contributors
# SPDX-License-Identifier: MIT
#
# File: cmake/distclean.py
# Brief: Remove a project build directory and its generated editor selection.

# Imports --------------------------------------------------------------------
import argparse
import json
from pathlib import Path
import shutil


def validate_build_directory(source_dir, build_dir):
    """Reject paths that are unsafe or do not belong to this source tree."""
    if build_dir.is_symlink():
        raise ValueError("BUILD_DIR must not be a symbolic link")
    build_dir = build_dir.resolve()
    if build_dir == source_dir or build_dir in source_dir.parents:
        raise ValueError("BUILD_DIR must not contain the source directory")
    if build_dir == Path.home().resolve():
        raise ValueError("BUILD_DIR must not be the home directory")

    if build_dir.exists():
        cache = build_dir / "CMakeCache.txt"
        if not cache.is_file():
            raise ValueError("BUILD_DIR must contain this project's CMakeCache.txt")
        home_prefix = "CMAKE_HOME_DIRECTORY:INTERNAL="
        cache_home = next(
            (line[len(home_prefix):] for line in cache.read_text().splitlines()
             if line.startswith(home_prefix)), None
        )
        if cache_home is None or Path(cache_home).resolve() != source_dir:
            raise ValueError("BUILD_DIR belongs to a different source directory")
    return build_dir


def remove_editor_selection(source_dir, build_dir):
    """Remove .clangd only when it selects the deleted build directory."""
    editor = source_dir / ".clangd"
    if editor.is_file() and not editor.is_symlink():
        config = editor.read_text()
        database = f"  CompilationDatabase: {json.dumps(str(build_dir))}"
        if (config.startswith("# Generated by CMake;")
                and database in config.splitlines()):
            editor.unlink()
            print(f"Removed {editor}")


# Build directory cleanup ----------------------------------------------------
def distclean(source_dir, build_dir):
    """Remove one verified build tree and its generated editor selection."""
    source_dir = source_dir.resolve()
    build_dir = validate_build_directory(source_dir, build_dir)

    if build_dir.exists():
        shutil.rmtree(build_dir)
        print(f"Removed {build_dir}")
    else:
        print(f"Build directory already absent: {build_dir}")

    # Preserve editor selections for other builds and manually authored files.
    remove_editor_selection(source_dir, build_dir)


# Command-line entry ---------------------------------------------------------
def main():
    """Parse cleanup paths and report validation failures without a traceback."""
    parser = argparse.ArgumentParser(
        description="Remove a project build directory and its generated editor selection."
    )
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--build-dir", type=Path, required=True)
    args = parser.parse_args()
    try:
        distclean(args.source_dir, args.build_dir)
    except (OSError, ValueError) as error:
        parser.exit(1, f"distclean: {error}\n")


if __name__ == "__main__":
    main()
