# Copyright (c) 2026 simple-boot contributors
# SPDX-License-Identifier: MIT
#
# File: cmake/generate_artifacts.py
# Brief: Export boot images, ELF memory diagrams, and editor configuration.

# Imports --------------------------------------------------------------------
import argparse
import html
import json
import os
from pathlib import Path
import subprocess
import tempfile

# Diagram geometry -----------------------------------------------------------
SVG_WIDTH = 1160
SVG_HEIGHT = 870
SVG_ROW_HEIGHT = 92
SVG_ROW_GAP = 12
SVG_REGION_COLORS = (
    "#f59e0b", "#2dd4bf", "#475569", "#60a5fa", "#475569", "#c084fc"
)

# Output helpers -------------------------------------------------------------
def atomic_write(path, text):
    """Publish complete files, including when different builds share .clangd."""
    path = Path(path)
    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent,
                                     delete=False) as output:
        temporary = Path(output.name)
        output.write(text)
    try:
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def update_editor(source_dir, build_dir):
    """Point clangd at the compilation database of the active build."""
    config = (
        "# Generated by CMake; the latest configured or built directory is active.\n"
        "CompileFlags:\n"
        f"  CompilationDatabase: {json.dumps(str(build_dir))}\n"
        "  Remove: [-fno-tree-loop-distribute-patterns]\n"
    )
    atomic_write(source_dir / ".clangd", config)
    atomic_write(build_dir / "clangd.config", config)


def tool_output(tool, *arguments):
    """Run a binutils tool with stable, locale-independent text output."""
    return subprocess.check_output([tool, *map(str, arguments)],
                                   universal_newlines=True, encoding="utf-8",
                                   env={**os.environ, "LC_ALL": "C"})


# ELF layout -----------------------------------------------------------------
def read_symbols(readelf, elf):
    """Return all defined ELF symbols as a name-to-address mapping."""
    symbols = {}
    for line in tool_output(readelf, "-W", "-s", elf).splitlines():
        fields = line.split()
        if len(fields) >= 8 and fields[0].endswith(":") and fields[6] != "UND":
            try:
                symbols[fields[7]] = int(fields[1], 16)
            except ValueError:
                continue
    return symbols


def memory_layout(symbols, arch):
    """Build a serializable memory-layout model from linker symbols."""
    def region(name, start, end, used=None):
        """Resolve and validate one half-open linker-defined region."""
        low, high = symbols[start], symbols[end]
        if high < low:
            raise ValueError(f"Invalid {name} region: {low:#x}..{high:#x}")
        return {"name": name, "start": low, "end": high, "capacity": high - low,
                "used": used}

    regions = [
        region("Code", "__region_code_start", "__region_code_end",
               symbols["__code_end"] - symbols["__code_start"]),
        region("RO data + initializers", "__region_ro_start", "__region_ro_end",
               symbols["__ro_image_end"] - symbols["__region_ro_start"]),
        region("Reserved", "__region_ro_end", "__region_rw_start"),
        region("RW data + BSS", "__region_rw_start", "__region_rw_end",
               symbols["__bss_end"] - symbols["__region_rw_start"]),
        region("Reserved", "__region_rw_end", "__stack_bottom"),
        region("Stack", "__stack_bottom", "__stack_top"),
    ]
    boundaries = [
        ("CODE_START", "CODE_END"), ("RO_DATA_START", "RO_DATA_END"),
        ("RO_DATA_END", "RW_DATA_START"), ("RW_DATA_START", "RW_DATA_END"),
        ("RW_DATA_END", "STACK_END"), ("STACK_END", "STACK_START"),
    ]
    for item, (start_label, end_label) in zip(regions, boundaries):
        item.update(start_label=start_label, end_label=end_label)
    sections = []
    for name, start, end in [
        ("Code and vectors", "__code_start", "__code_end"),
        (".rodata", "__rodata_start", "__rodata_end"),
        (".data load image (LMA)", "__data_load_start", "__ro_image_end"),
        (".data runtime (VMA)", "__data_start", "__data_end"),
        (".bss", "__bss_start", "__bss_end"),
        ("Stack allocation", "__stack_bottom", "__stack_top"),
    ]:
        sections.append(region(name, start, end))
    return {"architecture": arch, "address_bits": 64 if arch == "aarch64" else 32,
            "end_addresses_exclusive": True, "regions": regions, "sections": sections}


# SVG diagram ----------------------------------------------------------------
def render_svg(layout):
    """Render a schematic map; equal row heights keep sparse maps legible."""
    digits = layout["address_bits"] // 4

    def address(value):
        return f"0x{value:0{digits}x}"

    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" '
             f'viewBox="0 0 {SVG_WIDTH} {SVG_HEIGHT}" '
             'role="img" aria-labelledby="title description">',
             '<title id="title">Boot memory map</title>',
             '<desc id="description">High addresses at the top. Region heights are '
             'schematic, not to scale. End addresses are exclusive.</desc>',
             '<rect width="100%" height="100%" rx="18" fill="#0f172a"/>',
             '<g font-family="ui-monospace, monospace" fill="#e2e8f0">',
             '<text x="36" y="48" font-size="28" font-weight="bold">Boot memory map</text>',
             f'<text x="36" y="78" font-size="15">{html.escape(layout["architecture"])} '
             '| ELF-derived layout | high addresses at top</text>',
             '<text x="36" y="108" font-size="13" fill="#94a3b8">'
             'Schematic heights; usage bars show linked bytes / region capacity.</text>']
    colored_regions = zip(layout["regions"], SVG_REGION_COLORS)
    for index, (region, color) in enumerate(reversed(list(colored_regions))):
        y = 138 + index * (SVG_ROW_HEIGHT + SVG_ROW_GAP)
        parts += [f'<rect x="36" y="{y}" width="650" '
                  f'height="{SVG_ROW_HEIGHT}" rx="9" '
                  'fill="#1e293b" stroke="#334155"/>',
                  f'<rect x="36" y="{y}" width="6" '
                  f'height="{SVG_ROW_HEIGHT}" fill="{color}"/>',
                  f'<text x="58" y="{y + 29}" font-size="19" font-weight="bold">'
                  f'{html.escape(region["name"])}</text>']
        used, capacity = region["used"], region["capacity"]
        detail = f'{capacity:,} bytes capacity'
        if used is not None:
            percentage = used / capacity * 100 if capacity else 0
            detail = f'{used:,} / {capacity:,} bytes ({percentage:.2f}%)'
            parts += [f'<rect x="58" y="{y + 72}" width="600" height="5" fill="#334155"/>',
                      f'<rect x="58" y="{y + 72}" width="{6 * percentage:.2f}" '
                      f'height="5" fill="{color}"/>']
        elif region["name"] == "Stack":
            detail += ' | grows downward; runtime usage unknown'
        end_text = f'{region["end_label"]:13} {address(region["end"])}'
        start_text = f'{region["start_label"]:13} {address(region["start"])}'
        parts += [f'<text x="58" y="{y + 54}" font-size="13" '
                  f'fill="#cbd5e1">{detail}</text>',
                  f'<text x="712" y="{y + 30}" font-size="14">'
                  f'{end_text}</text>',
                  f'<text x="712" y="{y + 59}" font-size="14">'
                  f'{start_text}</text>']
    parts += ['<text x="36" y="795" font-size="14">'
              'STACK_START = initial SP; STACK_END = low stack boundary.</text>',
              '<text x="36" y="822" font-size="13" fill="#94a3b8">'
              'Ends are exclusive. Reserved ranges are gaps, not evidence of installed RAM.</text>',
              '</g></svg>']
    return "\n".join(parts) + "\n"


def render_html(layout, svg, memory_map):
    """Embed the SVG and linked-section table in a standalone report."""
    rows = []
    for item in layout["sections"]:
        rows.append(f'<tr><td>{html.escape(item["name"])}</td><td>0x{item["start"]:x}</td>'
                    f'<td>0x{item["end"]:x}</td><td>{item["capacity"]:,}</td></tr>')
    return '''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Boot memory map</title>
<style>
body{margin:0;padding:24px;background:#020617;color:#e2e8f0;font:15px system-ui,sans-serif}
main{max-width:1160px;margin:auto}svg{width:100%;height:auto}a{color:#7dd3fc}
table{width:100%;border-collapse:collapse;margin:24px 0}th,td{padding:12px;text-align:left;
border-bottom:1px solid #334155}td:not(:first-child){font-family:monospace}
.scroll{overflow-x:auto}h2{font-size:20px}p{color:#94a3b8}
</style><main>''' + svg + '''
<p><a href="''' + memory_map + '''.svg" download>Download SVG</a> &middot;
<a href="''' + memory_map + '''.json" download>Download layout JSON</a></p>
<h2>Linked contents</h2><div class="scroll"><table>
<thead><tr><th>Contents</th><th>Start</th><th>End (exclusive)</th><th>Bytes</th></tr></thead>
<tbody>''' + "".join(rows) + '''</tbody></table></div>
<p>Data initializers are loaded into RO and copied to RW before application entry.
Stack allocation does not measure runtime stack usage.</p></main></html>
'''


# Build exports --------------------------------------------------------------
def generate(args):
    """Generate editor metadata and, when requested, image artifacts."""
    build = args.build_dir.resolve()
    update_editor(args.source_dir.resolve(), build)
    if args.editor_only:
        return
    elf = args.elf.resolve()
    output_prefix = args.image_name
    symbols = read_symbols(args.readelf, elf)
    layout = memory_layout(symbols, args.arch)
    for output_format, suffix in (("binary", "bin"), ("ihex", "hex")):
        subprocess.run([args.objcopy, "-O", output_format, str(elf),
                        str(build / f"{output_prefix}.{suffix}")], check=True)
    atomic_write(build / f"{output_prefix}.asm",
                 tool_output(args.objdump, "-d", "-S", "-w", elf))
    svg = render_svg(layout)
    memory_map = f"{output_prefix}-memory-map"
    atomic_write(build / f"{memory_map}.json", json.dumps(layout, indent=2) + "\n")
    atomic_write(build / f"{memory_map}.svg", svg)
    atomic_write(build / f"{memory_map}.html", render_html(layout, svg, memory_map))
    print(f"Generated {output_prefix} images, disassembly, and memory map.")


def main():
    """Parse command-line options and run artifact generation."""
    parser = argparse.ArgumentParser(
        description="Export boot images, memory maps, and clangd configuration."
    )
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--editor-only", action="store_true")
    parser.add_argument("--elf", type=Path)
    parser.add_argument("--image-name")
    parser.add_argument("--arch", choices=("aarch64", "aarch32", "cortex-m"))
    for name in ("objcopy", "objdump", "readelf"):
        parser.add_argument(f"--{name}")
    args = parser.parse_args()
    if not args.editor_only and not all((args.arch, args.elf, args.image_name,
                                         args.objcopy, args.objdump, args.readelf)):
        parser.error("image generation requires --arch, --elf, --image-name, "
                     "--objcopy, --objdump, and --readelf")
    generate(args)


if __name__ == "__main__":
    main()
